version: '3.3'

services:
  db:
    image: mariadb:10.5
    volumes:
      - db_data:/var/lib/mysql
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: e-bee
      MYSQL_DATABASE: e-bee
      MYSQL_USER: e-bee
      MYSQL_PASSWORD: e-bee

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    volumes:
      - ./e-bee:/var/www/html/wp-content/themes/e-bee
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: e-bee
      WORDPRESS_DB_PASSWORD: e-bee
      WORDPRESS_DB_NAME: e-bee

volumes:
  db_data: {}
